layout_spectrum: 0.01971326
color:
  saturation: 0.6933426
  brandStrength: 0
  lightness: 0.7040691
  rhythmicContrast: 0.5329747
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
typography_spectrum: 0
name: 'Sjarmøren Neo!'
